config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :articles
  end

  resources  :articles do
    resources :comments
  end
  get 'articles/index'
  get 'welcome/index'
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'all', to: 'articles#index_all'
  get 'tags/:tag', to: 'articles#index', as: :tag
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_taggable
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 5}

  def slug
    # Slug is the part of a URL that identifies a page
    # in human readable keywords
    substitutions = [
      [' ' , '-'],
      ['.' , '_'],
      ['?' , '']
    ]
    safe_title = title.downcase
    substitutions.each { |sub| safe_title.gsub!(sub[0],
                                                sub[1]) }
    return safe_title.parameterize
  end

  def to_param
    "#{id}-#{slug}"
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
#  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @articles = Article.order(:created_at)
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.tag_list.add("main") if @article.tag_list.empty?
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#  skip_before_action :authenticate_user!, only: [:index, :show]

  def index_all
    @articles = Article.all
    render 'index'
  end

  def index
    if params[:tag]
      articles = Article.tagged_with(params[:tag])
      @tag = params[:tag]
    else
      articles = Article.tagged_with("main")
    end
    @articles = articles.sort_by{ |e| e[:created_at] }

  end

  def show
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h3> <%= @tag if @tag.present? %> </h3>

<% @articles.reverse_each do |article| %>
<div class="article-div">
  <%= link_to(article) do %>
    <h2><%=  article.title %></h2>
  <% end %>
  <i> <%= article.user.name.capitalize %> </i> <br>
  <%=  raw(article.body.truncate(300, omission: '....</p>'))  %> 
  <%= link_to 'Show More', article_path(article) %> <br>
  <strong> <%= pluralize(article.comments.count, 'Comments') %>  </strong>
</div>
<% end %>

app/views/articles/show.html.erb
<div class="article-div">
    <h2> <%= @article.title %> </h2>
    <i> <%= @article.created_at.to_formatted_s(:short) %> </i> <br>
    <%= User.find(@article.user_id).name.capitalize %>
    <div class="article-body">
        <%= raw(@article.body) %>
    </div>
    <h3> Tags </h3>
    <p>
        <%= raw(@article.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ')) %>
    </p>
    <% unless current_user.nil? || !current_user.is_admin? %>
        <h3> Admin Tools<h3>
        <p>
            <%= link_to 'Edit', edit_admin_article_path(@article) %>
            <%= link_to 'Destroy', admin_article_path(@article),
                                                method: :delete,
                                                data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
    <h2>Comments</h2>
    <%= render @article.comments %>
    <% unless current_user.nil? %>
        <%= render "comments/form" %>
    <% end %>
    <%= link_to 'Home', controller: 'articles' %>
</div>