config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :articles
  end

  resources  :articles do
    resources :comments
  end
  get 'articles/index'
  get 'welcome/index'
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'all', to: 'articles#index_all'
  get 'tags/:tag', to: 'articles#index', as: :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_taggable
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 5}

  def slug
    # Slug is the part of a URL that identifies a page
    # in human readable keywords
    substitutions = [
      [' ' , '-'],
      ['.' , '_'],
      ['?' , '']
    ]
    safe_title = title.downcase
    substitutions.each { |sub| safe_title.gsub!(sub[0],
                                                sub[1]) }
    return safe_title.parameterize
  end

  def to_param
    "#{id}-#{slug}"
  end

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    #:url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    #:path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :comments
  has_many :articles

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
#  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @articles = Article.order(:created_at)
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.tag_list.add("main") if @article.tag_list.empty?
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  protect_from_forgery with: :exception
#  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
#  skip_before_action :authenticate_user!, only: [:index, :show]

  def index_all
    @articles = Article.all
    render 'index'
  end

  def index
    if params[:tag]
      articles = Article.tagged_with(params[:tag])
      @tag = params[:tag]
    else
      articles = Article.tagged_with("main")
    end
    @articles = articles.sort_by{ |e| e[:created_at] }

  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    current_user.comments << @comment
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = DeployTestSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
#  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_headerbar.html.erb
<div class="header-bar max-header-bar">
    <span class="header-bar-icon">
        <%= image_tag "hamburger_icon.svg", class: "header-bar-img normal" %>
    </span>
    <span class="header-bar-main">
        <%= link_to 'Home', root_path, class: "headerbar-link", method: :get %>
        <%= link_to 'About', welcome_index_path, class: "headerbar-link" %>
        <%= link_to 'Posts', articles_path, class: "headerbar-link" %>
    </span>
    <ul class="header-bar-list">
        <li> <%= link_to 'Home', root_path, class: "headerlist-link", method: :get %>
            <li> <%= link_to 'About', welcome_index_path, class: "headerlist-link" %>
                <li> <%= link_to 'Posts', articles_path, class: "headerlist-link" %>
                    <% if current_user %>
                        <li><%= link_to 'Logout', destroy_user_session_path, class: 'userinfo-link', method: :delete %>
                            <% if current_user.is_admin? %>
                                <li> <%= link_to 'New Post', new_admin_article_path, class: 'userinfo-link', method: :get %>
                                    <li> <%= link_to 'List Posts', admin_articles_path, class: 'userinfo-link', method: :get %>
                            <% end %>
                    <% else %>
                            <li> <%= link_to 'Login', new_user_session_path, class: 'userinfo-link', method: :get %>
                                <li> <%= link_to 'Create User', new_user_registration_path, class: 'userinfo-link'%>
                    <% end %>

    </ul>
</div>

app/views/layouts/_userbar.html.erb
Welcome<%= ' ' + current_user[:name].capitalize if current_user %>! <br>
<% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path, class: 'userinfo-link', method: :delete %>
    <% if current_user.is_admin? %>
        <%= link_to 'New Post', new_admin_article_path, class: 'userinfo-link', method: :get %>
        <%= link_to 'List Posts', admin_articles_path, class: 'userinfo-link', method: :get %>
    <% end %>
<% else %>
<%= link_to 'Login', new_user_session_path, class: 'userinfo-link', method: :get %>
<%= link_to 'Create User', new_user_registration_path, class: 'userinfo-link'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
        <meta name="viewport" content="width=device-width;
                                       initial-scale=1.0;
                                       maximum-scale=1.0;
                                       minimum-scale=1.0;
                                       user-scalable=no;
                                       target-densityDpi=device-dpi" />

        <meta name="description" content="">
        <meta name="author" content="Nicholas Yang">
        <title>Horribly Underqualified</title>
        <%= favicon_link_tag %>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="<%= controller_name %><%= action_name%>">

        <div class="header">
            <%= link_to root_path, :class => 'header-link' do %>
            <h1> Horribly Underqualified </h1>
            <div class="tagline">
              Because I have no idea what I'm talking about
            </div>
                <% end  %>
        </div>

        <%= render 'layouts/headerbar' %>

        <div class="user-bar">
            <%= render 'layouts/userbar' %>
        </div>
        <% if flash[:notice] || flash[:alert] %>
            <div class="alert-bar">
                <h2 id="notice">
                  <%= flash[:notice] %>
                  <%= flash[:alert] %>
                </h2>
            </div>
            <% end %>
            <div class="body">
            <%= yield %>
            </div>
    </body>
</html>

app/views/shared/_form.html.erb
<!-- Doesn't work right now because stupid rails routes aren't adjustable  -->

<% if @article.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
        </h2>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<p>
    <%= f.label :title %><br>
    <%=  f.text_field :title %>
</p>
<p class="ckeditor" >
    <%= f.label :body %><br>
    <%= f.cktext_area :body, cols: 100, rows: 10 %>
</p>
<p>
  <%= f.label :tag_list %><br>
  <%= f.text_field :tag_list %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>